# Generated by Django 5.2.1 on 2025-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_laboratoire_pharmacien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratoire',
            old_name='date_inscription',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='medecin',
            old_name='date_inscription',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='date_inscription',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pharmacien',
            old_name='date_inscription',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='horaires',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='horaires',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='horaires',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='numero_ordre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacien',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
