# Generated by Django 5.2.1 on 2025-05-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_date_inscription_laboratoire_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
