# Generated by Django 5.2.1 on 2025-05-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rendezvous_lien_visio_disponibilite_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='email_professionnel',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medecin',
            name='email_professionnel',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='email_professionnel',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
