# Generated by Django 4.2.13 on 2025-05-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_laboratoire_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='numero_agrement',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medecin',
            name='services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pharmacien',
            name='numero_ordre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='horaires',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(default='generaliste', max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='tarif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
