# Generated by Django 4.2.13 on 2025-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_laboratoire_numero_agrement_medecin_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medecins/'),
        ),
    ]
