# Generated by Django 4.2.13 on 2025-05-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medecin'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
